### ISSUE TITLE
Not compatible with new java 17. :v 

### ISSUE THREAD

**Issue by Khikki** [Roadhog360/Et-Futurum-Requiem#102]
Version: 2.3.2

[lastest.log
](https://gist.github.com/Khikki/6eae3b1a2bca1c2640271b57c95f0183)

I'm experimenting and trying to build assembly 1.7.10 on Java Version: 17. Etfuturum Req. is the only one that I can't run, can you tell me about it?

Use Java 17.

Yes, I know that this is not supposed to be, but I try to get a maximum of 1.7.10.

**Comment by GregoriusT** [comment]
I would love to look at the Log File but you posted it with Hastebin which is notoriously broken, cant you paste it with a Gist on GitHub or Pastebin?

**Comment by makamys** [comment]
I didn't even know you could run 1.7.10 with a Java version higher than 8. When I try with OpenJDK 17.0.1, I get a crash before LaunchWrapper can even do anything. I'm curious how you managed to get it to run at all.

**Comment by Radviger** [comment]
We use weird java hackery through jni to unlock cross-module access. We also use class transformers to redirect reflection calls in mods to our own methods. As much as I can understand that weird crash, it's probably due to some class loading issues (because of multiple classloaders or smth). The most weird part is that a bytecode exception is thrown rather that java one. What's even weirder is that there are no such issues on 1.12 version even when we're using mixins.

**Comment by makamys** [comment]
So you're using a compatibility layer of sorts? Can you share it if it's public? It's pretty difficult for us to understand the issue otherwise.

I looked inside `asm-all-6.0_BETA.jar` and noticed `ClassReader`'s constructor throws an `IllegalArgumentException` if the major version of the class file is greater than 53. That's likely what's happening. I don't know which class is causing it, though.
Try running the game with the JVM args `-Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingFiner=true`, and post your `fml-client-latest.log` (if it's too big, just post a chunk surrounding `java.lang.ClassNotFoundException: ganymedes01.etfuturum.EtFuturumMixinPlugin`).

If your 1.12 instance has a newer version of ASM, that could explain why the issue doesn't happen there. Do other 1.7.10 mixin mods (e.g. BugTorch, Campfire Backport, Serene Seasons) work?

**Comment by Radviger** [comment]
We've managed to fix this issue by updating to asm 9.2, thanks!
