### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by makamys** [Roadhog360/Et-Futurum-Requiem#123]
Currently the mod crashes on a server due to three problems:

- [x] IIcon is accessed in some constructors (I fixed this one)
- [x] MixinBlockFurnace is applied even on the server: https://github.com/Roadhog360/Et-Futurum-Requiem/blob/8b011b72ff5df6156d7b61197db3f8a03e2fb3ae/src/main/java/ganymedes01/etfuturum/EtFuturumMixinPlugin.java#L105-L107
- [ ] Item#getSubItems (which is client-only) is called during oredict population: https://github.com/Roadhog360/Et-Futurum-Requiem/blob/8b011b72ff5df6156d7b61197db3f8a03e2fb3ae/src/main/java/ganymedes01/etfuturum/EtFuturum.java#L521

**Comment by Roadhog360** [comment]
Gotta love how many useful functions are pointlessly marked as clientside for no reason so I have to copy the code myself, ugh

**Comment by Roadhog360** [comment]
Unsure of what to do about getSubItems but it's the only way to do what I want, maybe I'll have to delay the fully-working composter because of this pointlessly client-sided function :/

**Comment by Roadhog360** [comment]
Closing this with composters put on the backburner due to this unfortunate oversight.

**Comment by GregoriusT** [comment]
Wait why the heck are you using getSubItems for that?!?

And why do you not just use OreDictionary events for the starts with "compostChance" thing?

And why do you seriously use something like "substring of item id contains words" for Composter Recipe creation? Is instanceof and the OreDict for "listAllseed", "treeSapling" and "treeLeaves" not enough?

Not to mention that if it is a Vanilla Item you seriously should MANUALLY register that and not through a laggy Iterator. I see things are so specific as to checking if something contains "pie" or "cake", which would result in "pietzo crystals" and "yellowcake" being compostable, or any form of Seed Oil for that matter.

Wait why do you change the itemID you got from the Registry to getUnlocalizedName of the Item, when there is SubItems??? There is a massive logic flaw there if you treat those interchangeably.

Yeah the whole "itemID.contains("whatever")" thing is deeply flawed and not using the OreDictionary at all, which was made for this purpose. Why cant you check for Ores that start with "crop" to get Compat with Harvestcraft and such?

Just so many problems with that piece of Code. This is something to completely rewrite from scratch, preferably without ANY iteration of anything, and using OreDicitonary Events to determine crops and compostchances, while also registering vanilla Items to the OreDict manually with the "compostChanceXX" thing (preferably with a timing that is after you registered your event handler in your Mods Constructor).

Anyways, there is lots of points I made here, I would recommend reading them again multiple times when a rewrite eventually happens, just to make sure you didnt miss anything. ;)

**Comment by Roadhog360** [comment]
Without getSubItems we have no way to know what the items alternate types are.

I do not want to register it manually because then we lose support for modded items.

Metadatas have the same namespace, they are the same ID so we have no way to tell them apart so I used the unlocalized name instead.

Many items don't have the specific enough oreDict tags needed to get the correct chances from it, my code works fine and the extremely low edge cases you described can easily jus thave an exception added in for them like I did with juices.

And laggy? It runs once on startup and an iterator runs thousands of times in a single second. Where on earth would there be so many registered items where this would take more than 2 seconds to run at startup? This isn't laggy at all.

You are overreacting. I need a new way to get the item subtypes but this will not be rewritten.

**Comment by GregoriusT** [comment]
> Without getSubItems we have no way to know what the items alternate types are. The only issue is it's clientside, but you state even if it wasn't I shouldn't do that? Why not? Isn't this exactly what I want for checking the sub types of an item? The modder literally registers their items here as a sub type, they are telling me these are the sub types I want. It is exacly the info I need. I don't need to attempt to build a subtypes list myself because it is very hard to do that. And I don't know how to automatically detect what an item's valid subtypes are anyways.

This is ABSOLUTELY NOT how it works at all whatsoever. getSubItems only exists for Creative Tabs and Creative Tabs ONLY. Nobody "registers" items there for other Modders at all. This is NOT the Info you want even, that is what OreDictionary was made for!
The OreDictionary is where Modders tell other Modders what their Items are and what to use them for.

> I do not want to register it manually because then we lose automatic support for modded items.

I said register the VANILLA Items manually, and then use the OreDictionary to do the Automatic Registering. This is what the OreDictionary was made for, and what everyone uses it for.

> Metadatas have the same namespace, they are the same ID so we have no way to tell them apart so I used the unlocalized name instead. I understand they are not the same. That is exactly why we need to change between them, Greg. The namespace generally seems to have a more accurate name of the item when it has no subtypes. But when we need to check the subtypes we simply have no choice. Checking the name space for all meta would just be stupid and give us the same exact result over and over. And we check the instance too because just that isn't enough. Sometimes the items didn't contain the right key words in their name and other times didn't extend the right classes and made their own. Some types of a specific block tend to just make their own class as for one reason or another there are a few where extending the vanilla class may be too restricted.

Scanning for Sub Items is wrong in the first place, you cant just assume the name of an Item means ANYTHING. The OreDictionary contains all the Data you want, why dont you scan THAT instead of the Item Registry?

> Many items don't have the specific enough oreDict tags needed to get the correct chances from it, my code works fine and the extremely low edge cases you described can easily jus thave an exception added in for them like I did with juices.

Then do not scan those Items by their Names, scan them by their instanceof BlockBush or so. Seriously the Names are NOT the way to go there. The OreDictionary would have given you 99.9% of actually correct results. And for a Composter, you just need to check for any OreDict tag that involves "treeSapling", "treeLeaves",  anything that starts with "crop", "seed" or "leaf", maybe even "food" but then ofcourse you can always have exceptions by using the OreDict for "listAlljuice" ontop of the startswith "food" one to exclude the Juices. Pam registered her Foods to the OreDictionary for this exact purpose and you just ignore that?
Not to mention you could check if the "instanceof ItemFood" in question is a Fluid Container for any Mod other than Harvestcraft.

> And laggy? It runs once on startup and an iterator runs thousands of times in a single second. Where on earth would there be so many registered items where this would take more than 2 seconds to run at startup? This isn't laggy at all.

You are doing a REVERSE OreDictionary lookup for your composting chances there.

> You are overreacting. I need a new way to get the item subtypes but this will not be rewritten.

Good luck not rewriting that without making everything Server incompatible, since getSubItems does not exist there. And even if it did through ASM or mixin hackery, I know that some Mods would crash because they assume Clientside Stuff "exists".

> The vanilla items are registered the exact way I want them to under my iterator, why would I save 0.0002 seconds by registering them manually, make no difference in load time and waste my time? And without an iterator I cannot automatically support many modded items. Unless you want to write that huge list, I will pass on the rewrite.

So you want to add compatibility for other Mods adding specifically melons? This is NOT ABOUT PERFORMANCE, this is about catching Items in the crossfire that are not meant to be hit whatsoever, just because you want to iterate over specific Vanilla Items in a way that wont even add Mod Compat at all in the majority of cases?

> Oh no, one pietza crystal from a mod can be composted! Seriously, I've never even heard of that, what the hell is this stretch of an edge case? I extensively tested this with a handful of mods and adjusted the list and conditions to avoid this kind of stuff. Not like I can add a quick exception to that anyways or anything.

So
A: `constant List maintenance of special cases, where literally only Vanilla is supported properly, because Mods do not use Item IDs or Item Names to distinguish their Stuff (many use Indexed Numbers instead)`
Or
B: `Since only Vanilla is supported properly anyways, why not just add the Entries for Vanilla things and leave the Metadata alone, because it is ignored by your code most of the time anyways, and doesn't even catch half the Mods Greg knows about`
Or
C: `Just rewrite using the OreDictionary, so that more Mods are supported in the first place, in the way they make sense to be supported, since it is what everyone intended to use it for. This also removes all the wrong hits you would need to special case for.`

I wonder what will cost the least effort of those three.

I got a LOT of years worth of constant List maintenance behind me, so I would not suggest Option A whatsoever.

As for Option B, If your ambition was to catch ALL modded Items, good luck, this Iterator doesn't even catch half of the ones I know of, while likely hitting some wrong ones, which is why I suggested using the OreDictionary in the first place to improve the coverage.

Option C saves you most of the work, because Modders do/did the work FOR YOU!

Remember please that i am NOT telling you this because Performance (that one is probably okayish still).
I am telling you this, because I see where you are going and how much unneeded maintenance you are going to have to do with your approach.
Not to mention all the Items your approach doesn't cover, like any Mod Item that uses Metadata is NOT caught, because Mods do the "modname:theirmetaitem:135" thing for their Stuff, which will not contain ANY Strings you could possibly be looking for, because Modders are lazy and dont want to have the unlocalized name be anything other than in the style of "theirmetaitem.135", which does not contain any useful information. I should know, because I am one of those!

Lots of rambling, I know. ;)

-----

Also Piezo Crystals are the Quartz thing in Microphones that do all the Audio to Electricity Conversion. Same goes for "Quartz" Watches/Clocks and the thing that controls the clocks of your Computer Processing Unit.
🏳️‍🌈 The more you know! 🏳️‍🌈 ⭐

**Comment by Roadhog360** [comment]
Already explained why I don't just use OreDict in my post. And I tell you why instance checks are not enough, an item I want to select over a specific meta would instead hit ALL of the items. I wrote it this way for a very specific reason to ensure we are not selecting the wrong item. You tell me to read your whole post so I did, please pay me the same courtesy.

You think it won't add mod compat in the majority of cases when that is completely wrong; have you even tried it? I sure have.

If you think this is going to hit modded items wrongly, feel free to provide some axtual example from mods so I can add exceptions to them.

As far as I am concerned this update needs to come out so this feature is getting delayed anyways. This update is very late and has been suffering from "let's add this this this and rewrite this this and this and this" and is months overdue never releasing and never finishing any of those features. I will now be closing discussion here, this is currently not up for debate. Maybe I will be free to talk about this when I'm ready to re-implement it. I do not have the time or energy to completely rewrite the system that was working fine.

**Comment by GregoriusT** [comment]
Please be aware that I am trying to use lengthy and repetitive explanations to get my point across.

> Already explained why I don't just use OreDict in my post.

Have you tried using ALSO OreDict to get better coverage? It has a LOT of things in it including a ton of Foods and Crops.

> And I tell you why instance checks are not enough, an item I want to select over a specific meta would instead hit ALL of the items

So instead you will hit a very complex amount of random Items. If you want support for other MetaDatas than just 0 or Wildcard, then you have to manually look at each thing, at which point I remind you, it's literally making a List.

> I wrote it this way for a very specific reason to ensure we are not selecting the wrong item

You say you are being careful when selecting Items, but what i see is quite the very opposite of careful.
Careful would be looking at each Mod and making a manual List, while also using OreDict to fill in the gaps for Mods you did not look at.
Checking for "instanceof ItemFood && if it isn't a Fluid Container (or a Pam Juice)" is also a perfectly valid addition to those things.

> You tell me to read your whole post so I did, please pay me the same courtesy.

That was for the purpose of you forgetting half of it, which I remind you happened a lot in the past when I explained things. ;)

> Just because the subtypes is meant for Creative doesn't mean it couldn't have been used for other things if it wasn't clientsided. I'm sure we've all gotten creative with what a line of code is and isn't meant for when using it, and it's literally a list of the subtypes the item is supposed to have. It was exactly what I wanted, what's wrong with that?

The wrong part is that you thought it was what you wanted. The moment you scan through that List, even if it existed Serverside, you dont know what is actually inside of it.
And the moment you scan for unlocalized Names within that List containing certain buzzwords is where you go too far and hit either of these three: Errors, literally Everything or literally Nothing.

You know the Motto of many famous Companies?
"move fast and break things, and forget about fixing them later"
This is what you are doing with this.
I am trying to tell you to be actually careful about what you are doing, because the way you are doing it now does not even do what you want it to do.

> OreDict is meant to have broad categories and they may not be specific enough for what I need

What? You can literally register whatever you want to the OreDict as long as you follow some basic conventions. What category does the OreDict not have that you seriously need to be very precise about? Because it has Foods, Crops and Tree Parts, which pretty sure are all the compostable things that exist.

> Many types of food or plant didn't have a tag specifically for them

If you are talking about Mods not registering their shit, I know that Issue very well, but I have seen a ton of complex cases where a lot of different things are in the same Item as very unrelated Materials like Ingots.

> but I guarantee you if I only used dict tags I would see why it didn't work for my use case and go right back to the way I was doing it. I know I checked all these different things for a reason.

DO NOT confuse this with me telling you to ONLY use OreDict, I told you 3 things that when combined do a relatively good Job at covering everything. The instanceof Iteration is perfectly fine, that could easily be kept and advanced on.

It is the getSubItems and getUnlocalizedName part that are the Issue. That and that you Iterate over Vanilla things as if you did not know they exist.

> You think it won't add mod compat in the majority of cases when that is completely wrong; have you even tried it? I sure have.

Clearly didn't try it with GregTech did ya. :P
And I register all my Stuff to the OreDict, so you ignoring the OreDict in favor of ONLY using that Iteration process is quite wasteful to everyone who uses/used the OreDict to help others with their Recipes.

> If you think this is going to hit modded items wrongly, feel free to provide some actual example from mods so I can add exceptions to them.

At that point you should just make a List in the first place. Don't you realize that you adding exceptions via Blacklist is just as much if not way more effort than a proper Whitelist?

> And in your first post you comment about how the iterator is laggy, so I comment how it isn't, and then suddenly you say it isn't about performance. So why bring up that it is supposedly laggy in the first place when it isn't and that apparently isn't even the problem?

It is not the problem I am referring to. That is why it is not relevant. Just because I used the adjective "laggy" once (due to the reverse OreDict lookup), doesn't mean all focus should be put on that.

> As far as I am concerned this update needs to come out so this feature is getting delayed anyways. This update is very late and has been suffering from "let's add this this this and rewrite this this and this and this" and is months overdue never releasing and never finishing any of those features. I will now be closing discussion here, this is currently not up for debate. Maybe I will be free to talk about this when I'm ready to re-implement it. I do not have the time or energy to completely rewrite the system that was working fine.

What? This Issue is not a blocker for Releases, apart from trivially having to disable some but not all of your Code temporarily due to the Crash ofcourse. You can easily just Release without fixing this first.

Why does everyone frikkin think "issue need instant fix NAOW, fix is waste time of dev stuff, issue make release later" when someone brings up any sort of issue? Seriously, not all Issues need to be fixed instantly, take your time, and stop assuming everyone wants an instant fix that delays the release, geez.

> One compromise I may have to reach here is loading the game with hundreds of popular mods, generating a list to a file using this code, doing some slight cleanup and maybe just making that the default list, only having used this code to initially generate the list.

Yeah your Code might be somewhat okayish for you making the initial Manual List, but you will likely miss a lot of things if you dont look closely.

I would still recommend supplementing a `Manual List` with `OreDict` and `instanceof ItemFood that isn't a Fluid Container or a Pam Juice` and `other instanceof alike` checks.

Just please avoid the whole getSubItems/getUnlocalizedName/ReverseOreDict stuff in the actual final Code.

-----

This wall of text is supposed to be informative and help fixing actual problems.
Used Language is just mannerisms of Greg and doesn't reflect any sort of social opinion.

This thing took a second hour to write, yeesh... well, have an unsarcastic nice day. ;D

**Comment by Roadhog360** [comment]
I think I may be misunderstanding your point then. When I am ready to look at compostables again it may be time to give your post a complete re-read.
