### ISSUE TITLE
Crash on world join

### ISSUE THREAD

**Issue by Asveste** [Roadhog360/Et-Futurum-Requiem#138]
**Starting Questions**
- [X] This is a mod incompatibility, if I use this in vanilla Forge, with only Et Futurum Requiem installed it works as I'd expect it to.

Version: Et Futurum Requiem 2.4.0 Release Candidate 1

If this is a crash, please upload the report: https://gist.github.com/Asveste/03dd64b626f43a46e483ee7ea1763761

**Describe the bug**
Same as in the title, when trying to join my world the game crashes.

**To Reproduce**
1. Start the game
2. Join a world
3. The game crashes

**Mod Incompatibilities**
_If this was a mod incompatibility, what are the possible suspects? If you're not 100% sure, you can still list your suspected mods here, just tell me if you're not certain they actually cause it._
Maybe some mods from Reika, but they're really well programmed so I don't think so.

**Mod List**
_If you have posted a crash report above or this is not a mod incompatibility, you can skip this._

**Comment by Roadhog360** [comment]
This appears to be an issue with the CodeChicken chunk loaders

**Comment by Roadhog360** [comment]
I'm attempting to investigate and fix this now. 

`from Reika, but they're really well programmed`

Haha, funny.

**Comment by Asveste** [comment]
I... don't know which one of us used irony right now (or if it even was irony from you xD).

**Comment by Roadhog360** [comment]
Reika's mods have been infamous among my Discord's users for being buggy.

**Comment by Asveste** [comment]
Oh, thats very surprising to hear (no, seriously)!
I never had any problems with any of Reikas mods (and I pretty much have all of them installed), so it's interesting to hear about others experiences with Reikas mods for once :)

**Comment by GregoriusT** [comment]
Sorry to join in on this sort of thing, but "Reika" and "Quality" do not go into a sentence. I had to deal with a LOT of his Bugs over the years, and damn you cant make some of this stuff up...

One of his startup time lags was because he was "pinging the MIDI interfaces of the Computer one by one, sequentially, by a list of a few dozen known MIDI device IDs, letting each ping timeout after long time", please note physical MIDI devices dont exist anymore since the 90s, so the likelihood any MIDI device gets successfully found is near zero. And even if it does find one MIDI device, it still pinged the other few dozen ones regardless, all with the long ping timeout. [He eventually fixed that Issue though](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1965), because someone found out that there was 0% CPU usage for a long time during the startup of MC (since the MIDI stuff was waiting for a ping timeout).

**Comment by Asveste** [comment]
I guess the reason for me never having any issues is because I only started playing with Reikas mods about 1½ years ago and by that time the most serious stuff got fixed? But thats just a random assumption from me ^^

I just like Reikas mods due to the uniqueness they offer which is really rare with recent mods; also I'm not a modder or anything, meaning I can't judge the mods from this sort of perspective, so thanks for the little eye-opening comment!

**Comment by Roadhog360** [comment]
When the build finishes, can you please try the jar here that is not marked as "dev" in the package folder?

https://github.com/Roadhog360/Et-Futurum-Requiem/actions/runs/2605941287

**Comment by Roadhog360** [comment]
That's all I need to know. On the previous build, I was able to instantly reproduce the issue when I activated a chunk loader and then rejoin the world.
