### ISSUE TITLE
very slow loading

### ISSUE THREAD

**Issue by FanRenLa** [Roadhog360/Et-Futurum-Requiem#171]
**Starting Questions**
- [ ] This is a mod incompatibility, if I use this in vanilla Forge, with only Et Futurum Requiem installed it works as I'd expect it to.

_Please specify the actual version... please don't just say "latest", tell me the version number of the mod in-game, or the name the jar had when downloading it._
Version:2.4.0
If this is a crash, please upload the report:

**Describe the bug**
_A clear and concise description of what the bug is._
very slow loading

**Mod Incompatibilities**
_If this was a mod incompatibility, what are the possible suspects? If you're not 100% sure, you can still list your suspected mods here, just tell me if you're not certain they actually cause it._

**Mod List**
_If you have posted a crash report above or this is not a mod incompatibility, you can skip this. If you're filling this out because of a mod incompatibility that isn't a crash, crash reports generate a mods list you can copy. Please use Pastebin if it is large. If you don't have an up-to-date crash report, you can hold F3 + C for 10 seconds while in a world to crash the game, which will give you a crash report._

**Screenshots**
![image](https://user-images.githubusercontent.com/83486178/187040774-897e13fe-18fb-49b4-a4f3-799d2a6016f8.png)

**Additional context**
Any other info I may have missed. If you know the code which causes the error please post a link to it.

**Comment by FanRenLa** [comment]
Loading speed is very slow

**Comment by Roadhog360** [comment]
Please properly fill out the template.

**Comment by FanRenLa** [comment]
> 请正确填写模板。
> 
> 你在使用 EndlessID 吗？

no

**Comment by FanRenLa** [comment]
> > 请重新填写模板。
> > 你在使用 EndlessID 吗？
> 
> 不

only it one (mod)(Google Translate)

**Comment by GregoriusT** [comment]
Where is the Crash Report? You know, that one File that is supposed to contain the Data about the Crash.

**Comment by makamys** [comment]
Judging from the screenshot, this is because [AssetDirector](https://github.com/makamys/MCLib/wiki/AssetDirector) is downloading sounds. Don't worry about it, it only happens the first time you launch the mod.

**Comment by FanRenLa** [comment]
> 崩溃报告在哪里？你知道，那个文件应该包含有关崩溃的数据。

Not crashing, just slow loading (Google translate)

**Comment by FanRenLa** [comment]
> 从屏幕截图来看，这是因为[资产Director](https://github.com/makamys/MCLib/wiki/AssetDirector)正在下载声音。别担心，它只发生在你第一次启动mod的时候。

I already know that, but it's not friendly to modpacks (Google translate)

**Comment by Roadhog360** [comment]
Why not?

**Comment by FanRenLa** [comment]
> 为什么不呢？

Give it to others, and others will download it again.
unless all packed.
In fact, it's okay, you can pack it directly.
But the download is really slow, even after downloading, give it to others, but the first download is really slow.

**Comment by FanRenLa** [comment]
> > 为什么不呢？
> 
> 把它交给其他人，其他人会再次下载它。除非全部打包。事实上，没关系，你可以直接打包。但是下载真的很慢，即使下载后，也要把它交给别人，但第一次下载真的很慢。

You know, I'm definitely not the only one with slow downloads

**Comment by Roadhog360** [comment]
I am not going back to packing 100MB of sounds in the jar. Would you rather download it once or every time there is an update?

These are downloads for vanilla sounds. They would be just as slow as the assets you downloaded when launching 1.7.10 for the first time. Are vanilla game asset downloads also not friendly to modpacks?

**Comment by FanRenLa** [comment]
I'm just giving feedback. As for the network, or why it doesn't really matter, I'll pack it all up for others.

> 我不会再把100MB的声音装在罐子里了。您是愿意下载一次还是每次更新时都下载它？使用此系统，您永远不会一遍又一遍地下载相同的声音，只有一次。
> 
> 这些是香草声音的下载。它们的速度与您首次启动1.7.10时下载的资产一样慢。香草游戏资产下载对modpack也不友好吗？
> 
> 这个系统实际上对慢速下载速度更友好。我们只是将下载内容移动到其他地方，除了整体下载更少之外，没有任何变化。

I know this, I just give feedback. As for my personal network, I actually know that the download is slow. I will package it all for others. This does not affect it.
I didn't react at first, thinking it was simply slow loading,It's not really that big of a problem.

**Comment by FanRenLa** [comment]
Later I reacted and found that I really needed to download other files.

**Comment by FanRenLa** [comment]
This is similar to the blueprint download of (Simulated town), in fact, I didn't think about the problem of downloading files at first.

**Comment by GregoriusT** [comment]
Oh right Roadhog, I forgot to mention that the great Firewall of China is going to block downloads in a really arsenine way, it will just void the packets meaning you have to actually wait until each and every access to your download thing times out. This can potentially take real life HOURS if you dont make sure that there is a fallback.

Back when I still used Dropbox for GregTech Stuff, this caused 7 minutes of extra loading time (ping timeout of 360 seconds) to chinese people simply because i tried downloading ONE tiny text file that was less than a few kilobytes in size.

There is a lot of problems when trying to auto-download things from websites that might be on the chinese blacklist. People then tend to use VPNs or TOR to download things ahead of time so they can play with their Friends.

**Comment by Roadhog360** [comment]
If my asset downloads are blocked, so are the vanilla ones. So your game is going to be missing a lot of things regardless.

I am not the developer of AssetDirector, however maybe @makamys could add a fallback to the downloads?

**Comment by tyrael93** [comment]
That definitely looks like a PRC issue more than an EFR issue :thinking:

**Comment by GregoriusT** [comment]
I fixed the Dropbox thing originally by just letting the download run in the background in a different thread (later I just used my own website, but kept the parallelization)

**Comment by FanRenLa** [comment]
> 这绝对看起来像是一个中国问题，而不是一个EFR问题。🤔



> 这绝对看起来像是一个中国问题，而不是一个EFR问题。🤔

That's right, at first, the network was slow

**Comment by Roadhog360** [comment]
These downloads cannot be threaded because they have to be ready by the time the game loads in assets.

**Comment by GregoriusT** [comment]
You could start the download in preinit, and then have the thread join when it is needed for the assets. Would at least save "some" time. Especially on bigger Modpacks. ;)

**Comment by makamys** [comment]
> If my asset downloads are blocked, so are the vanilla ones.

Not necessarily, if Chinese players use a custom launcher that grabs the assets from somewhere else 🤔 

> could add a fallback to the downloads

What do you mean by this?

Anyway, I can think of one way to fix this. We could use the modpack's `.minecraft/asset_director` directory to store the assets if the directory exists. The new search order for assets would be:
```diff
+ * `<modpack dir>/asset_director/assets/objects`
  * `<launcher's assets dir>/objects`
  * `<AssetDirector dir>/objects`
```
Meaning: the modpack's `asset_director` directory overrides anything else if it exists.

And the new order for selecting the AssetDirector dir would be:
```diff
  * `<minecraft.sharedDataDir>/asset_director`, if the `minecraft.sharedDataDir` JVM argument is set.
  * `$MINECRAFT_SHARED_DATA_DIR/asset_director`, if the `MINECRAFT_SHARED_DATA_DIR` environmental variable is set.
+ * `<modpack dir>/asset_director`, if it exists
  * `<launcher's assets dir>/../asset_director`, if the legacy launcher is used. (This is a workaround for it deleting extra files from the assets directory.)
  * Otherwise, `<launcher's assets dir>/asset_director` is used.
  ```
Meaning: the modpack's `asset_director` directory overrides anything else if it exists, unless the user configured things otherwise.

Thus, modpack creators could distribute assets in the following way: the modpack creator would create an `asset_director` directory in the instance directory, and launch the game, letting the assets get downloaded there. Then when publishing the pack, they would include that directory. Users would not need to download assets, only the pack creator, since the ones in this directory would be used.

Does that sound good?

To be clear, this wouldn't be the recommended way of doing things normally, only for special cases like this one.

**Comment by GregoriusT** [comment]
With Fallback I mean some Addon Mod (or just a zip file) that you can manually download if the auto-download does not work. Basically it will try to download from that Addon Mod first, and THEN do Internet Downloads for anything that is missing. You basically did suggest just unzipping something into the asset_director directory, which is practically the same thing.

Also maybe have the download timeout be only like 60 seconds instead of the huge default value.

**Comment by Roadhog360** [comment]
> > could add a fallback to the downloads
> 
> What do you mean by this?

What do you mean what do I mean? You were the one who suggested that

**Comment by makamys** [comment]
> With Fallback I mean some Addon Mod (or just a zip file) that you can manually download if the auto-download does not work

Ah, got it. We'd like to avoid distributing so many Mojang assets, but like you said, my suggestion would effectively let pack authors do it themselves.

> Also maybe have the download timeout be only like 60 seconds instead of the huge default value.

The timeout for losing connection is only 10 seconds, and if one download fails, all further downloads will get aborted. There's no overall time limit though, so theoretically you could have a stable 1 B/s connection and take 4 years to download everything. But I don't think it's our business to limit that, it's up to the user to decide how much they are willing to wait before giving up.

> What do you mean what do I mean? Greg's the one who suggested that

My bad, I misread.

> Doesn't asset director always create an alternate folder?

It creates one per-launcher, not per-instance. By doing it per-instance, we let modpack authors bundle assets with the modpack, letting players avoid having to download them from Mojang.

**Comment by Roadhog360** [comment]
What happens if their instance is in `.minecraft`

**Comment by GregoriusT** [comment]
Sorry for the confusion, I mean basically what makamys just said.

**Comment by makamys** [comment]
> What happens if their instance is in `.minecraft`

Then we're screwed, good point. I should change the path to `<modpack dir>/local-data/asset_director` or something like that. (I'll think about the name.)
