### ISSUE TITLE
Raw copper has no output if EFR copper is off

### ISSUE THREAD

**Issue by Roadhog360** [Roadhog360/Et-Futurum-Requiem#177]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [x] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)
> _Specify the actual version, please don't just say "latest", tell us the version number of the mod in-game, or the name the jar had when downloading it._

2.4.1 CI [f0a1db5](https://github.com/Roadhog360/Et-Futurum-Requiem/commit/f0a1db553cb8b20fb9991ca44f7a5d4eba45dfa9)

### Describe the issue (IMPORTANT)
> _A list of steps to reproduce the issue may be helpful too. Screenshots could also prove beneficial for visual issues._

If raw ores are enabled but the EFR copper is off, there's no way to smelt it to another mod's copper ingot. Expected result should be it just smelts to a different copper ingot.
Line 721 in ModRecipes is disabled when copper is off, but then there is no alternative present for raw copper only.

**Comment by Roadhog360** [comment]
Go fuck yourself

**Comment by GregoriusT** [comment]
Lol telling GitHub actions to screw with Issue Reports might not be the smartest thing to do, it might turn the slightest typo into an invalid template. XD

**Comment by Roadhog360** [comment]
It is in my best interest to make sure people provide all necessary information.

And besides, I looked at the action file and there was nothing actually checking if the issue used the template, so it must have been unconditionally closing the tickets.

**Comment by MikhailTapio** [comment]
Could that be done by simply getting 'OreDictionary.getOres("ingotCopper").get(0)'(if it exists) and adding it to the recipe result?

**Comment by Roadhog360** [comment]
That was the exact plan, yes.

**Comment by GregoriusT** [comment]
Yeah should work fine, I haven't seen any Mod that adds Copper Ore but doesn't also have Copper ingots,
so the Raw Copper Ore Item should be perfectly unobtainable if no Copper Ingots exist,
meaning this is a safe assumption to make as long as Mods have already registered their Ingots to the OreDict at the time you check the List of Copper Ingots,
because I have never seen a Mod registering specifically Ingots in PostInit or later (apart from MineTweaker, but that doesn't count).

Adding the Recipe in PostInit would be required for this to make sure it works.

Also make sure the List is not empty when you try to get(0), because it might end up with an Index Out of Bounds if no Copper exists whatsoever.

**Comment by Roadhog360** [comment]
Yes, that too.

The raw ores are intended to be compatible with modded copper ores in which the user may prefer another mod's ingot so it needs to be obtainable.
