### ISSUE TITLE
Crash with mods that reference fields of `ModBlocks` or `ModItems`

### ISSUE THREAD

**Issue by kotmatross28729** [Roadhog360/Et-Futurum-Requiem#272]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

Et_Futurum_Requiem-2.4.5-SNAPSHOT-323fdbf+nomixin

### Describe the issue (IMPORTANT)

Trying to create a world with immersivecavegen after commit a501170 will crash the game

### Crash report

https://pastebin.com/UFCVh7WE

**Comment by makamys** [comment]
The mod is looking for `ModBlocks.deepslate`, which doesn't exist anymore since that class got refactored into an enum. This issue is not exclusive to ICG, any mod that references EFR's blocks or items this way (e.g. [DMod](https://github.com/makamys/DMod/blob/86424f5a40bb0624181abede74d3eee8c7ff342b/src/main/java/makamys/dmod/compat/Compat.java#L69)) has stopped working.

**Comment by GregoriusT** [comment]
Which means all the references to ModBlocks that other Mods actually use, need to be added back, and there is no other way to fix it, because some of those Mods are already dead and therefore cannot be blamed, even if it is their fault for not using the normal way of getting other Mods Items.

**Comment by Roadhog360** [comment]
They should be using the proper way, I spent days doing this refactor, and I am looking to move away from archaic, old code styles that slowed me down immensely. Well I may be willing to implement a stand in class that uses the old field names, and rename the enums to something else. But that won't be my doing.

I understand this rewrite will introduce breaking changes, but I simply cannot stand the way all of the little annoyances in the code has piled up. After this rewrite, I will hopefully never do this again.

Usually when I close issues like this sometimes I'm just being stubborn, and getting a bit icky at mods that do things wrong, but this time it is something I am accepting as a small caveat for a better future that will make it easier to develop for me. To be able to progress further, and be able to get more done before the next burnout phase, I simply need this rewrite.

I am sorry, this will not be fixed by me. I will contact the immersive Cajun author if they are willing to change the way they reference my blocks. I already have permission to merge DMod in EFR anyways

**Comment by makamys** [comment]
Here's the full list of known instances of ModBlocks or ModItems fields being referenced in other mods. Check these boxes as fixes are made (either on EFR's side or the respective mod's side.)

A 💀 symbol is used to mark mods that are no longer officially maintained (necessitating a fix from EFR.)

- [ ] Immersive Cavegen
  - `ModBlocks.deepslate`
- [ ] D-Mod
  - `ModItems.sweet_berry_bush`
  - `ModBlocks.sweet_berry_bush`
- [ ] WTFCaveBiomes (💀)
  - `ModBlocks.prismarine`
  - `ModBlocks.sea_lantern`
  - `ModBlocks.red_sandstone`

**Comment by Roadhog360** [comment]
Thank you, I may introduce a few stand-in fields now that I know what ones are needed.

**Comment by Roadhog360** [comment]
Reopening since fixing does not require reverting the rewrite.

**Comment by Roadhog360** [comment]
Added temporary stand-in fields for the fix.

Even added ones for D-Mod so old versions don't end up crashing.
