### ISSUE TITLE
Compatible error with ExtraUtilities‘s Division Sigil

### ISSUE THREAD

**Issue by Ventivu** [Roadhog360/Et-Futurum-Requiem#311]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

2.4.6

### Describe the issue (IMPORTANT)

When mod replaced “Enchanting Table”, “Division Sigil” will not be activated from it‘s Description way

**Comment by Roadhog360** [comment]
Mod contains hardcoded check for the vanilla enchantment table rather than doing a proper check for enchantment tables. This issue is on their end. You can change the tile replacement mode to enable usage of both the Et Futurum Requiem enchantment table alongside the vanilla one, or disable the new enchantment tables altogether to get around this issue.
