### ISSUE TITLE
Iron Lanterns can't be placed on Slabs or Stairs

### ISSUE THREAD

**Issue by NomadThunder** [Roadhog360/Et-Futurum-Requiem#372]
Not sure, simple bug report. 

![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/121021543/04b9a76a-6cb5-4f77-a962-bc32ffd25fe5)
 
Lanterns can't be placed on Slabs and the bottom of Stairs.
 
I thought you could do that in Modern Craft for builds.

On the other hand, wouldn't mind being in contact with the team or working together to get this fine mod to best potential. I got some money I could donate to support the mod creators and their time to do what needs to be done; quicker and efficiently. This mod is one of the main cores to my strange old game, so the dedication is there.

**Comment by Roadhog360** [comment]
I am appreciative that you enjoy my work. If you want to support the creators:
https://ko-fi.com/roadhog360

https://ko-fi.com/embeddedt
https://ko-fi.com/jss2a98aj

**Comment by Roadhog360** [comment]
Wow, you are proposing quite a lot :o

Right now progress is a bit slow, because I got burnt out trying to make content that was a bit too difficult for me, as well as wanting to start a new mod that adds unique content, so I'm making new things instead of just backporting as well

As for your other project, I'd be happy to merge in any changes if you're willing to share them with me. You can find a Discord server in the description of the mod pages. Now that I think about it I should add it to GitHub as well. You're free to talk to me, and any financial contributions would certainly motivate me to work more on the mod. However I'd like to preface this by saying I have no guarantees in anything, and my motivation swings wildly from day to day.

https://discord.gg/AJxEFs6YBN

**Comment by NomadThunder** [comment]
I joined the group, can you add me so we can have a chat and figure things out? Simply a plan and what you can do for this and that?I figured it would let me PM but it doesn't seem to and can't add you unless you add me it seems. It would just be most convenient. Business haha. Likely would start with all the Blocks and Items you can in both areas or just yours, the easiest, quickest, and you get the most out of them I suppose. 
Wether you service Et Futurum for a price or aid me and my strange game (I can't do the modding, someone else does . . . ) I can really use the backporting services.
