### ISSUE TITLE
Pressure plates (in general) cannot be placed on Et Futurum fences.

### ISSUE THREAD

**Issue by happyburger23** [Roadhog360/Et-Futurum-Requiem#405]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.6.0-SNAPSHOT-634ffcf

### Describe the Issue

Pressure plates (default oak & the Et Futurum ones) cannot be placed on the other fence types. The only fences they can be placed on are Oak Fences. The other fences will not work.

1. Place an oak fence, then any other fence (a spruce fence, for example).
2. Craft any pressure plate
3. Place it on the oak fence (it will work)
4. Attempt to place it on a fence added by the mod (it won't work)

**Comment by Roadhog360** [comment]
This is an issue in vanilla pressure plate code, it has a hard-coded check for only the vanilla fence and wall, instead of properly doing an instance check. You will notice this happens to any modded fence or wall, not just mine.

Well this could be fixed with a mixing, that is a very Overkill solution for a very simple problem, so I will not fix it. This is up for a bug fix mod.

**Comment by Roadhog360** [comment]
Actually, this is already fixed in [BugTorch](https://modrinth.com/mod/bugtorch).
