### ISSUE TITLE
Et-Futurum-Requiem and Netherlicious are not compatible

### ISSUE THREAD

**Issue by jiahe666666** [Roadhog360/Et-Futurum-Requiem#427]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.5.1-nomixin

### Describe the Issue

KCauldron cannot start after Netherlicious is installed。
I'm sorry, because this should be Netherlicious's problem, since it has no place to submit the issue, it has no choice but to submit it here.
I didn't want to check the second box, but I found that I couldn't submit without checking it

### Other Details

[2024-02-20-7.log.gz](https://github.com/Roadhog360/Et-Futurum-Requiem/files/14345910/2024-02-20-7.log.gz)

**Comment by SilearFlare** [comment]
Netherlicious has a curseforge page you can submit issues to. Yes, it's not github, but I really don't see why you'd post this here.

**Comment by jiahe666666** [comment]
> Netherlicious 有一个 curseforge 页面，您可以向其提交问题。是的，它不是 github，但我真的不明白你为什么要在这里发布这个。

I'm terribly sorry. I was a little careless. Now I have changed the title.
我非常抱歉，我有点粗心。现在我已更改标题。

**Comment by Roadhog360** [comment]
KCauldron is not supported. Whilst Crucible is unsupported, it is suggested you switch to it as it is far more stable than KCauldron or Thermos. Also please do not ignore the second tick box and submit a hybrid server issue anyways, it is there for a reason :)

**Comment by jiahe666666** [comment]
> KCauldron is not supported. Whilst Crucible is unsupported, it is suggested you switch to it as it is far more stable than KCauldron or Thermos. Also please do not ignore the second tick box and submit a hybrid server issue anyways, it is there for a reason :)
> 
> It seems you understood what the second box meant, that means you do not submit the issue then

Thank you very much for your advice. I'll change it. But I still want to support KCauldron, Thermos, Crucible, Mohist.
I wish you happy and healthy every day

**Comment by Roadhog360** [comment]
Appreciate the well wishes. You too!
I can't support these hybrid servers because of the way they change and make patches that happen to break mods. However Crucible is based on Thermos, which is based on KCauldron. Crucible is objectively more updated and you should be using it. Crucible is not supported with Et Futurum Requiem issues, but I still recommend updating your hybrid server. Other people have reported using Crucible with Et Futurum perfectly fine and it seems to work a lot better for most people. Thermos and KCauldron are abandoned and do not get updates; Crucible still actively receives updates.
